version: '3.1'

services:

  gisportal:
    container_name: gisportal
    #image: container.pml.space/web-development/e-shape/dive-frontend
    build: gisportal
    ports:
      - "80:6789"
    volumes:
      - /usr/share/GISportal:/app/GISportal/config


