
/**
 * Setup the options for the gritter and create opening
 * welcome message.
 */
function setupGritter()
{
   $.extend($.gritter.options, { 
      position: 'bottom-right',
      fade_in_speed: 'medium',
      fade_out_speed: 800,
      time: 6000
   });
}

/**
 * Create the opening message that the user will see.
 */
function createWelcomeMessage()
{
   map.tutUID = showMessage('welcomeTutorial', null);
}

/**
 * Displays errors as gritter messages.
 * 
 * @param {Object} layer - The OpenLayers.Layer object, can be null.
 * @param {String} type - A short string describing the object that has error'd.
 * @param {Object} request - The request object generated by the error.
 * @param {Object} errorType - The errorType object generated by the error.
 * @param {Object} exception - The exception object generated by the error.
 */
function gritterErrorHandler(data)
{  
   if(data.request.status == 400)
   {
      showMessage('error400', data);
      return
   }
   else if (data.request.status == 500)
   {
      showMessage('error500', data);
      return
   }
   else if (data.errorType == 'parsererror')
   {
      showMessage('errorParserError', data);
      return
   }
   
   
   if(data.layer)
   {
      $.gritter.add({
         title: data.errorType.toUpperCase() + ': ' + data.request.status + ' (' + data.exception + ')',
         text: 'Could not get the ' + data.type + ' from the server for ' + data.layer.name + '. Try refreshing the page',
         //image: 'img/OpEc_small.png',
         class_name: 'gritter-light',
         sticky: true,
      });
   }
   else
   {
      $.gritter.add({
         title: data.errorType.toUpperCase() + ': ' + data.request.status + ' (' + data.exception + ')',
         text: 'Could not get the ' + data.type + ' from the server. Try refreshing the page',
         //image: 'img/OpEc_small.png',
         class_name: 'gritter-light',
         sticky: true,
      });
   }
}

/**
 * A logic function that tries to diagnose any problems 
 * with layers and show the correct help message.
 */ 
function gritterLayerHelper()
{      
   $(document).on('click', 'img[src="img/exclamation_small.png"]', function() 
   {
      var layerID = $(this).parent().parent().attr('id');
      var layer = map.getLayersByName(layerID)[0];
      var helpMessage = 'none';
      
      // Is the layer temporal?
      if(layer.temporal) {     
         var inst = $('#viewDate').datepicker('getDate'); // Get the selected date
        
         // If the date is set...
         if(inst != null) { 
            var thedate = new Date(inst.selectedYear, inst.selectedMonth, inst.selectedDay);
            var uidate = ISODateString(thedate);
            var mDate = layer.matchDate(uidate);

            // Can the layer display the selected date?
            if(mDate == null) {
               helpMessage = 'dateNotInRange';
            }
         }
         // If the date is not set...
         else if(inst == null) {
            helpMessage = 'noDate';
         }
      }

      var data = { layer: layer };
      showMessage(helpMessage, data);

      return false;
   });
}

/**
 * Creates all the help messages to be used.
 */
function createHelpMessages()
{
   // Opening welcome message
   map.helperMessages['welcomeTutorial'] = {
      title: function() {
         return 'Welcome to the Opec Portal';
      },
      text: function(layer) { 
         return 'It\'s great to have you here! First thing you need to do is decided what layers you want to use. You can do that from the ' +
         '<a id="wtHelp-layerSelectionPanel" href="#">layer selection panel</a>.' +
         ' If you have any trouble, you can always just hit the ' + 
         '<a id="wtHelp-questionMark" href="#">question mark</a>' + 
         ' at the top of most windows. When you are ready for the next step just click ' +
         '<a id="wtHelp-next" href="#">next</a>.';    
      },
      afterOpen: function(layer) {
         
         $('#wtHelp-layerSelectionPanel').click(function(e) {
            if($('#layerSelection').dialog('isOpen')) {
               $('#layerSelection').fadeTo('slow', 0.3, function() { $(this).fadeTo('slow', 1); });
            }
            else {
               $('#layerPreloader').fadeTo('slow', 0.3, function() { $(this).fadeTo('slow', 1); });
            }
            
            return false;
         });
         
         $('#wtHelp-questionMark').click(function(e) {
            $('.ui-dialog-titlebar-help:visible').effect("highlight", {}, 3000);  
            return false;
         });

         $('#wtHelp-next').click(function(e) {
            removeMessage(map.tutUID);
            map.tutUID = showMessage('layerTutorial', null);

            return false;
         });
      },
      max: 1,
   };
   
   // Layer panels
   map.helperMessages['layerTutorial'] = {
      title: function() {
         return 'Viewing Layers';
      },
      text: function() {
         return 'To view the layers you just selected, you need to use the ' +
         '<a id="ltHelp-layersPanel" href="#">layers panel</a> .' +
         'If you want to see a layer displayed on the map you need to select it\'s checkbox ' +
         'and then select a date (We will cover dates next!). When you are done with a layer just uncheck it. ' +
         'You can also right click on layers for further options. When you are ready for the next step just click ' +
         '<a id="wtHelp-next" href="#">next</a>.';
      },
      afterOpen: function() {
         $('#ltHelp-layersPanel').click(function() {
            $('.triggerL').trigger('click');
            return false;
         });
         
         $('#wtHelp-next').click(function(e) {
            removeMessage(map.tutUID);
            map.tutUID = showMessage('dateTutorial', null);

            return false;
         });
      },
      max: 1,
   }
   
   // Date Tutorial
   map.helperMessages['dateTutorial'] = {
      title: function() {
         return 'Selecting Dates';
      },
      text: function() {
         return 'To select a date to be used by temporal layers, click on the ' +
            '<a id="dtDatepickerBtn" href="#">datepicker</a>' +
            ' at the top of the screen. Then use the left and right arrows to ' +
            'change the month or use the dropdown boxes. You can also type a date into the textbox. ' +
            '<a id="dtNext" href="#">Next</a>.';
      },
      afterOpen: function() {
         // Open the data panel on click
         $('#dtNext').click(function(e) {
            removeMessage(map.tutUID);
            map.tutUID = showMessage('tbdTutorial', null);

            return false;
         });

         $('#dtDatepickerBtn').click(function() {
            $('#viewDate').datepicker("show").datepicker("show").effect("highlight", {}, 3000);
            return false;
         })
      },
      max: 1,
   };

   // To be Continued
   map.helperMessages['tbdTutorial'] = {
      title: function() {
         return 'To Be Continued';
      },
      text: function() {
         return 'Be sure to provide any feedback about these tutorials ' +
         '<a id="give-some-feedback" href="http://trac.marineopec.eu/wiki" target="_blank">here</a>. ' +
         'Are they useful? Easy to follow? Too long? Too short?';
      },
      max: 1,
   };

   // No date selected on date picker
   map.helperMessages['noDate'] = {
      title: function() {
         return 'You need to select a date';
      },
      text: function(data) { 
         return 'This layer is a temporal layer and requires a date to be selected. ' +
            'To select a date use the ' +
            '<a id="datepickerBtn" href="#">datepicker</a>' +
            ' at the top of the screen.';
      },
      afterOpen: function(data) {
         $('#datepickerBtn').click(function() {
            var date = $.datepicker.parseDate('dd-mm-yy', data.layer.lastDate);
            $('#viewDate').datepicker("option", "defaultDate", date).datepicker("show").effect("highlight", {}, 3000);
            return false;
         });
      },
      max: 1,
   };

   // The selected date is not supported by this layer
   map.helperMessages['dateNotInRange'] = {
      title: function() {
         return 'Select another date';
      },
      text: function(data) {
         return 'The date you have selected is not avaliable for this layer. ' +
            'This layer supports dates between ' +
            data.layer.firstDate + ' and ' + data.layer.lastDate + '.' +
            ' Try selecting another date that all layers share.';
      },
      max: 3,
   };
   
   // Layer Selector Tutorial
   map.helperMessages['layerSelector'] = {
      title: function() {
         return 'Layer Selection Tutorial';
      },
      text: function() {
         return 'The layer selector is made up of two parts. The ' +
            '<a id="help-selectedLayers" href="#">selected layers</a>' +
            ' panel and the ' +
            '<a id="help-availableLayers" href="#">available layers</a>' +
            ' panel. To select a layer, you can click the plus sign at the ' +
            'end of a layer or drag a layer from one side to the other. ' +
            'To deselect a layer you can click the minus sign at the end of ' +
            'the layer or again drag from one side to the other.';
      },
      afterOpen: function(data) {
         $('#help-selectedLayers').click(function() {
            $('#layers .selected').fadeTo('slow', 0.3, function() { $(this).fadeTo('slow', 1); });
            return false;
         });
         
         $('#help-availableLayers').click(function() {
            $('#layers .available').fadeTo('slow', 0.3, function() { $(this).fadeTo('slow', 1); });
            return false;
         });
      },
      max: 1,
   };
   
   // Graph Creator Tutorial
   map.helperMessages['graphCreatorTutorial'] = {
      title: function() {
         return 'Lets Create A Graph!';
      },
      text: function() {
         return 'To create a graph we need three things. The wcs server ' +
         'to query (BaseURL), the coverage to get and the type of graph ' +
         'we want to create. You can also provide a bbox and/or a time range. ' +
         'If you\'re creating a histogram you can also provide some bins, but ' +
         'if you don\'t some will be created for you.';
      }
   }
   
   // Scalebar Tutorial
   map.helperMessages['scalebarTutorial'] = {
      title: function() {
         return 'Scalebar Tutorial';
      },
      text: function() {
        return 'The scalebar allows you to change the range of values used using ' +
        'the slider or if you prefer the min and max boxes. If you need to increase ' +
        'the range just enter a bigger number in any of the text boxes.';
      },
      max: 1,
   };
   
   // Bounding box selection for graphs
   map.helperMessages['bbox'] = {
      title: function(){
         return 'Select a bounding box';         
      },
      text: function(){
         return   'Now select a bouding box on the map using the '+
                  '<a id="rect-bbox" href="#">rectangular bounding box drawing tool</a>.';
      },
      afterOpen: function(data) {
         $('#rect-bbox').click(function() {
            $('#box').next().effect("highlight", {}, 3000);
            return false;
         });
      },
      max: 1,
   };
   
   map.helperMessages['error400'] = {
      title: function(){
         return 'Error: Bad Request';         
      },
      text: function(data){
         return 'A bad request was made ' + 
         '<a id="url400" href="' + data.url + '" target="_blank">here</a>' + '.';
      },
      max: 1,
   }
   
   map.helperMessages['error500'] = {
      title: function(){
         return 'Error: Internal Server Error';         
      },
      text: function(data){
         return 'The server ' + 
         '<a id="url500" href="' + data.url + '" target="_blank">here</a>' + 
         ' has had an internal server error.';
      },
      max: 1,
   }
   
   map.helperMessages['errorParserError'] = {
      title: function(){
         return 'Parse Error: Unexpected character';         
      },
      text: function(data){
         return 'An unexpected character was received from "' + 
         '<a id="urlParserError" href="' + data.url + '" target="_blank">this</a>' +
         '" address.';
      },
      max: 1,
   }
}

/**
 * Shows a gritter message with the message details provided.
 * 
 * @param {Object} messageName - The message object to use for the message.
 * @param {Object} data - Any data needed for the message.
 * 
 * @return {Int} Returns the unique ID of the message created. 
 */
function showMessage(messageName, data)
{
   var uid;
   
   var message = map.helperMessages[messageName];
   // Check for a title
   if(typeof(message.title) == 'undefined')
      message.title = function() {
         return 'Sorry, No Help Message Found';
      };
   // Check for some text
   if(typeof(message.text) == 'undefined')
      message.text = function() {
         return 'Sorry, we could not find a help message for your problem. Please refer to any help documentation you have.'; 
      };
   // Check for an afterOpen method
   if(typeof(message.afterOpen) == 'undefined')
      message.afterOpen = function() {};
      
   if(typeof(message.max) == 'undefined')
      message.max = 1;

   // Add the gritter message
   uid = $.gritter.add({
      title: message.title(data),
      text: message.text(data),
      after_open: function() {
         message.afterOpen(data);
      },
      //image: 'img/OpEc_small.png',
      class_name: 'gritter-light',
      sticky: true, 
      group: messageName,
      max: message.max,
   });
   
   return uid;
}

/**
 * Removes the message found from the unique ID.
 * 
 * @param {String} messageName - The messageName of the message type to remove.
 */
function removeMessage(uid)
{
   $.gritter.remove(uid, {
      fade: false,
      speed: 'fast',
   });
}
